### ISSUE TITLE
Prevent PNH from setting parking lots to points

### ISSUE THREAD

**Issue by t0cableguy** [WazeUSA/WME-Place-Harmonizer#16]
This is related to pnh matching. the script is setting parking lots to categories that are matched to a pnh place.

**Comment by mapomatic** [comment]
This happens because the Parking Lot category is overwritten by the chain's category(s).  It's impossible to change the place back to a Parking Lot once that happens.  I'm not sure when it's actually converting from an area to a point.  I wasn't able to duplicate that, but at least one tester experienced that.  The biggest problem (aside from user annoyance) is that there is or will be underlying data attached to PLA's that will be lost when they're accidentally converted to a different category.  I am going to temporarily disable PLA checks completely until we can get a better handle on it.

**Comment by t0cableguy** [comment]
from what I see this is only happening to new parking lots with pnh matching. Its setting the category for the pnh item. Its not changing it to a point, just turning it back into a regular place. However there is no way to convert it back to parking lot.

**Comment by t0cableguy** [comment]
temporarily fixed by disabling all pnh checks on PLA's

**Comment by mapomatic** [comment]
I'm reopening this since it isn't fixed, just disabled.

**Comment by mapomatic** [comment]
Fixed in v1.1.54
