### ISSUE TITLE
Refactor all code

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#30]
This is an internal enhancement that RavenDT and I believe would help code readability / stability, eliminate some bugs, and help prevent new ones from appearing.

This will be a big undertaking, so deciding on when / how to implement will be important.  I recommend that we finish tackling any MAJOR bugs, then work on a refactoring plan.  Once we are ready to start, create a new branch off of Beta.  Any minor bug fixes done in Beta after that point should also be fixed in the new branch so they are not re-introduced later.

We believe this should be done as soon as possible, while maintaining the major functionality in the Beta version, i.e. ignore minor Issues as much as possible until the refactoring is complete, and add a "this is in the refactored code" comment to any Issues that are solved during refactoring.

Let's discuss further, once all major bugs are tackled...

**Comment by mapomatic** [comment]
... and go ahead and start documenting any refactoring ideas / suggestions in this discussion thread.

**Comment by RavenDT** [comment]
Issues #7 and #31 have to do with the time handling code.  It appears that the way the code is written in the `checkHours()` function it is prone to issues.  I tried changing the syntax multiple times in order to fix the issue of the `hourSet` being undefined after the first "Add Hours" run.

`checkHours()` is run quite often, not just by adding hours.  It is run every time `harmonizePlace()` gets called so it can check for issues with overlapping hours.

I think this code can be rebuilt, minimized and made more efficient which would reduce execution time.

**Comment by mapomatic** [comment]
In hindsight, it will be difficult to keep track of what is done and what remains to be done in this discussion thread.  I've added a milestone and a label so we can try to track refactor-related issues.  Add both to any refactor issues/ideas/questions/etc.  We can change it up later if it's not working for us.

@RavenDT, can you take your comment above and either add it to an existing issue, or add a new one (if you believe it's refactor-related)?

**Comment by mapomatic** [comment]
I'm learning as I go... Added a refactor project so we can more easily see what is to-do, in progress, and done.  Can be sorted as we see fit.  Might help us to stay focused on the task(s) at hand rather than staring at a long list of issues and trying to filter them.
