### ISSUE TITLE
Refactoring: typescript 

### ISSUE THREAD

**Issue by StormeHawke** [WazeUSA/WME-Place-Harmonizer#47]
This is a radical idea, but I think a good one. Typescript is a definitely typed version of Javascript that my team at work uses. We code in TS and then use the typescript transpiler to render as plain Javascript. 

Running this way has all but eliminated the plague of runtime type errors that Javascript is prone to because type errors are caught by the IDE. Also gives you excellent intellisense capability. 

Like I said we've had a lot of success with typescript at work and I personally think it takes most of the pain of Javascript out of the equation while keeping its flexibility

**Comment by StormeHawke** [comment]
Not sure how to edit this when mobile so I'll finish my thought here. 

Like I said we've had a lot of success with typescript at work, and I personally think it takes most of the pain of Javascript out of the equation while keeping its flexibility

**Comment by RavenDT** [comment]
I'm not sure that the advantages that TypeScript has to offer would really have much of an impact in this project.  Also, I am pretty sure that most of the people working on WMEPH use an IDE that supports TypeScript intellisense [as you type].

Also, we'd have to compile every time we made a modification.
And we'd all have to learn a new "language".

Just my 2¢.

**Comment by mapomatic** [comment]
I agree with Raven (although the coder inside me is not happy because I like learning new languages).  If we were starting from scratch and had a dedicated team of developers that were either already familiar with TS or willing to learn it -- and we had some assurance we would be around for a while --, I would be on board 100%.  I think it's best to stick with the lowest common denominator in this case (JS).

**Comment by RavenDT** [comment]
Closing issue.
